### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by humenda**
This ports the library to Python3, with minimal changes.

### CODE REVIEW

**Comment by nbingham1** [comment]
I thought I had already created a branch somewhere with python3 support, the one I just uploaded isn't tested, let me look around a bit. I know I've been using a python3 version of this library in a few other projects. If I can't find it then I'll test your branch and merge. Either way, I'll get that all done by EOD tomorrow.

**Comment by nbingham1** [comment]
Ah, I did already update master for python3, I just hadn't updated the readme. I switched the parser to lxml, which does a much better job with websites that don't actually follow the rules for html tags. Check to see if the new instructions in the readme work for you and then I can close this PR. I'll check the remaining changes in the "python3" branch to see what's going on, but I suspect it's actually unrelated. It may be a few more features that I had added in for another project.

**Comment by humenda** [comment]
Thanks!

TBH, I've did this work to use hocr2html. Do you have a Python port of this as
well? Otherwise I'd do it and check whether this would work with master of
pyhtml.

**Comment by nbingham1** [comment]
Well, I did some work to do the conversion, there are probably bugs introduced, I'm not sure it's going to be able to do what you are imagining. hocr2html is largely heuristic, so it does the best it can to merge bounding boxes... hocr is pretty messy ultimately and hocr2html was pretty experimental. You'll have to fiddle with it to get it where you want it.

**Comment by humenda** [comment]
Ok, I see. I have had an interest in using it, but for actual development, I
do lack the time. If you say it's too immature, I'm afraid I won't be able to
use it.

Thanks anyway!

**Pull request closed without merging**
